import PadThai from "../images/padthai.jpg";
import Momo from "../images/momo.jpg";
import Kimbab from "../images/kimbab.jpg";
import Bibimbap from "../images/bibimbab.jpg";
import Ramen from "../images/Ramen.jpg";
import KimchiFriedRice from "../images/KimchiFriedRice.jpg";
import Pho from "../images/Pho.jpg";
import VeganFalafelWrap from "../images/vegan-falafel-wrap.jpg";
import GlutenFreeQuinoaSalad from "../images/gluten-free-quinoa-salad.jpg";
import CoronationEggSando from "../images/CoronationEggSando.jpg";
import SaltedChocolateHazelnutBrownies from "../images/SaltedChocolateHazelnutBrownies.jpg";
import LemonSpongeCake from "../images/LemonSpongeCake.jpg";
import GlutenFreeMuffins from "../images/GlutenFreeMuffins.jpg";
import VeganBananaBread from "../images/VeganBananaBread.jpg";
import FrenchToast from "../images/FrenchToast.jpg";
import BerryYogurtBowl from "../images/BerryYogurtBowl.jpg";
import DanDanNoodles from "../images/DanDanNoodles.jpg";
import HoneyGarlicSalmon from "../images/HoneyGarlicSalmon.jpg";

const API = [
  {
    id: 1,
    title: "Pad Thai",
    image: PadThai,
    servings: "2",
    readyInMinutes: 30,
    vegan: "false",
    glutenFree: "false",
    dairyFree: "false",
    likes: "130",
    rating: "0.5",
    cuisine: "Thai",
    dishType: ["lunch", "dinner", "snacks"],
    summary:
      "Pad Thai is a popular stir-fried noodle dish from Thailand. It typically includes rice noodles, vegetables, tofu, shrimp, and a savory sauce made with tamarind, fish sauce, and palm sugar. The dish is often garnished with peanuts, lime wedges, and fresh herbs.",
    instruction: "Lorem",
  },
  {
    id: 2,
    title: "Momo",
    image: Momo,
    servings: "4",
    readyInMinutes: 60,
    vegan: "false",
    glutenFree: "false",
    dairyFree: "false",
    likes: "200",
    rating: "4.0",
    cuisine: "Nepalese",
    dishType: ["lunch", "dinner", "snacks", "appetizer"],
    summary:
      "Momos are a type of steamed dumpling that originated in Tibet and are popular in Nepal, Bhutan, and the Himalayan regions of India. They are made with a variety of fillings, such as vegetables, chicken, lamb, or beef, and are typically served with a spicy dipping sauce.",
    instruction: "Lorem ipsum",
  },
  {
    id: 3,
    title: "Kimchi Fried Rice",
    image: KimchiFriedRice,
    servings: "2",
    readyInMinutes: 25,
    vegan: "true",
    glutenFree: "false",
    dairyFree: "true",
    likes: "95",
    rating: "0.5",
    cuisine: "Korean",
    dishType: ["lunch", "dinner"],
    summary:
      "Kimchi fried rice is a popular Korean dish made with leftover rice, kimchi, vegetables, and often a fried egg on top. It's a great way to use up leftovers and adds a spicy kick to your meal.",
    instruction: "Lorem ipsum",
  },
  {
    id: 4,
    title: "Bibimbap",
    image: Bibimbap,
    servings: "2",
    readyInMinutes: 35,
    vegan: "false",
    glutenFree: "false",
    dairyFree: "false",
    likes: "130",
    rating: "2",
    cuisine: "Korean",
    dishType: ["lunch", "dinner"],
    summary:
      "Bibimbap is a Korean rice bowl dish that typically includes rice, mixed vegetables, meat, and a fried egg on top. It's often served with gochujang, a spicy chili sauce, and sesame oil for added flavor.",
    instruction: "Lorem ipsum",
  },
  {
    id: 5,
    title: "Pho",
    image: Pho,
    servings: "4",
    readyInMinutes: 180,
    vegan: "false",
    glutenFree: "false",
    dairyFree: "true",
    likes: "310",
    rating: "4.5",
    cuisine: "Vitenam",
    dishType: ["lunch", "dinner"],
    summary:
      "Pho is a Vietnamese noodle soup that typically includes rice noodles, vegetables, and meat (such as beef or chicken) in a savory broth. It's often served with herbs and spices, such as basil, cilantro, and lime.",
    instruction: "Lorem ipsum",
  },
  {
    id: 6,
    title: "Ramen",
    image: Ramen,
    servings: "2",
    readyInMinutes: 40,
    vegan: "false",
    glutenFree: "false",
    dairyFree: "false",
    likes: "130",
    rating: "2.5",
    cuisine: "Korean",
    dishType: ["snacks", "appetizer"],
    summary:
      "Ramen is a Japanese noodle soup dish that typically includes wheat noodles, vegetables, and meat (such as pork or chicken) in a flavorful broth. It's often served with toppings such as nori, boiled eggs, and green onions.",
    instruction: "Lorem ipsum",
  },
  {
    id: 7,
    title: "Kimbab",
    image: Kimbab,
    servings: "2",
    readyInMinutes: 40,
    vegan: "false",
    glutenFree: "false",
    dairyFree: "false",
    likes: "10",
    rating: "0.5",
    cuisine: "Korean",
    dishType: ["snacks", "appetizer"],
    summary:
      "Kimbab is a Korean dish that typically includes wheat noodles, vegetables, and meat (such as pork or chicken) in a flavorful broth. It's often served with toppings such as nori, boiled eggs, and green onions.",
    instruction: "Lorem ipsum",
  },
  {
    id: 8,
    title: "Gluten-Free Quinoa Salad",
    image: GlutenFreeQuinoaSalad,
    servings: "6",
    readyInMinutes: 20,
    vegan: "true",
    glutenFree: "true",
    dairyFree: "true",
    likes: "15",
    rating: "4.0",
    cuisine: "International",
    dishType: ["salad"],
    summary:
      "This Gluten-Free Quinoa Salad is packed with fresh vegetables, cooked quinoa, and a tangy vinaigrette dressing. It's a healthy and delicious option for a light lunch or dinner.",
    instruction: "Lorem ipsum",
  },
  {
    id: 9,
    title: "Vegan Falafel Wrap",
    image: VeganFalafelWrap,
    servings: "2",
    readyInMinutes: 30,
    vegan: "true",
    glutenFree: "false",
    dairyFree: "true",
    likes: "18",
    rating: "4.8",
    cuisine: "Mediterranean",
    dishType: ["lunch"],
    summary:
      "This Vegan Falafel Wrap is a delicious Mediterranean dish made with homemade falafel balls, fresh vegetables, and a creamy tahini sauce. It's a flavorful and satisfying option for a quick and healthy meal.",
    instruction: "Lorem ipsum",
  },
  {
    id: 10,
    title: "Coronation Egg Sando",
    image: CoronationEggSando,
    servings: "2",
    readyInMinutes: 15,
    vegan: "false",
    glutenFree: "false",
    dairyFree: "false",
    likes: "25",
    rating: "3.5",
    cuisine: "British",
    dishType: ["lunch", "snacks"],
    summary:
      "Coronation Egg Sando is a British classic sandwich filling made with hard-boiled eggs, curry powder, mayonnaise, and a touch of mango chutney. It's typically served on white bread with lettuce and is a perfect addition to any brunch or lunch spread.",
    instruction: "Lorem ipsum",
  },
  {
    id: 11,
    title: "Salted Chocolate & Hazelnut Brownies",
    image: SaltedChocolateHazelnutBrownies,
    servings: "8",
    readyInMinutes: 45,
    vegan: "false",
    glutenFree: "false",
    dairyFree: "false",
    likes: "40",
    rating: "4.7",
    cuisine: "International",
    dishType: ["dessert", "snacks"],
    summary:
      "Salted Chocolate & Hazelnut Brownies are rich and fudgy brownies with a perfect balance of sweet and salty flavors. They are loaded with chocolate chunks and toasted hazelnuts, making them a decadent treat for chocolate lovers.",
    instruction: "Lorem ipsum",
  },
  {
    id: 12,
    title: "Lemon Sponge Cake",
    image: LemonSpongeCake,
    servings: "10",
    readyInMinutes: 60,
    vegan: "false",
    glutenFree: "false",
    dairyFree: "false",
    likes: "65",
    rating: "4.5",
    cuisine: "International",
    dishType: ["dessert"],
    summary:
      "Lemon Sponge Cake is a light and fluffy dessert with a refreshing lemon flavor. It has a delicate texture and is perfect for any special occasion or afternoon tea. The cake is made with fresh lemon zest and juice for a tangy and citrusy taste.",
    instruction: "Lorem ipsum",
  },
  {
    id: 13,
    title: "Gluten Free Muffins",
    image: GlutenFreeMuffins,
    servings: "12",
    readyInMinutes: 40,
    vegan: "false",
    glutenFree: "true",
    dairyFree: "true",
    likes: "78",
    rating: "4.2",
    cuisine: "International",
    dishType: ["breakfast", "snacks"],
    summary:
      "Gluten-Free Muffins are delicious and fluffy muffins made without gluten-containing ingredients. They are perfect for those with gluten sensitivities or following a gluten-free diet. These muffins can be customized with various flavors and add-ins, such as blueberries, chocolate chips, or nuts.",
    instruction: "Lorem ipsum",
  },
  {
    id: 14,
    title: "Vegan Banana Bread",
    image: VeganBananaBread,
    servings: "8",
    readyInMinutes: 60,
    vegan: "true",
    glutenFree: "false",
    dairyFree: "true",
    likes: "152",
    rating: "4.5",
    cuisine: "International",
    dishType: ["breakfast", "snacks"],
    summary:
      "Vegan Banana Bread is a moist and delicious bread made without eggs or dairy products. It's a great way to use up ripe bananas and enjoy a sweet treat. This vegan version of banana bread is packed with flavor and can be enjoyed by vegans and non-vegans alike.",
    instruction: "Lorem ipsum",
  },
  {
    id: 15,
    title: "French Toast",
    image: FrenchToast,
    servings: "2",
    readyInMinutes: 20,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    likes: "98",
    rating: "4.5",
    cuisine: "French",
    dishType: ["breakfast"],
    summary:
      "French Toast is a classic breakfast dish that is loved for its simplicity and deliciousness. It's made by soaking bread slices in a mixture of eggs, milk, and a touch of vanilla, then cooking them to golden perfection on a griddle or pan. Serve with a sprinkle of powdered sugar, a drizzle of maple syrup, and fresh berries for a delightful morning treat.",
    instruction: "Lorem ipsum",
  },
  {
    id: 16,
    title: "Berry Yogurt Bowl",
    image: BerryYogurtBowl,
    servings: "1",
    readyInMinutes: 10,
    vegan: false,
    glutenFree: true,
    dairyFree: false,
    likes: "42",
    rating: "4.2",
    cuisine: "International",
    dishType: ["breakfast", "snacks"],
    summary:
      "This Berry Yogurt Bowl is a refreshing and nutritious breakfast or snack option. It's made with a base of creamy yogurt topped with a variety of fresh berries, crunchy granola, and a drizzle of honey. It's packed with antioxidants, vitamins, and fiber, making it a delicious and healthy choice to start your day.",
    instruction: "Lorem ipsum",
  },
  {
    id: 17,
    title: "Dan Dan Noodles",
    image: DanDanNoodles,
    servings: "2",
    readyInMinutes: 30,
    vegan: false,
    glutenFree: false,
    dairyFree: true,
    likes: "120",
    rating: "4.7",
    cuisine: "Chinese",
    dishType: ["lunch", "dinner"],
    summary:
      "Dan Dan Noodles are a popular Chinese street food dish known for their spicy and savory flavors. The noodles are typically served in a spicy sauce made with chili oil, Sichuan peppercorns, soy sauce, and other seasonings. They are often topped with minced pork or ground beef, chopped scallions, and crushed peanuts. Dan Dan Noodles offer a perfect balance of heat, umami, and texture, making them a delicious and satisfying meal.",
    instruction: "Lorem ipsum",
  },

  {
    id: 18,
    title: "Honey-Garlic Glazed Salmon",
    image: HoneyGarlicSalmon,
    servings: "2",
    readyInMinutes: 25,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    likes: "85",
    rating: "4.5",
    cuisine: "International",
    dishType: ["dinner"],
    summary:
      "Honey-Garlic Glazed Salmon is a delicious and healthy seafood dish that features tender salmon fillets coated in a sweet and savory glaze. The glaze is made with a combination of honey, garlic, soy sauce, and other flavorful ingredients. The salmon is baked or grilled to perfection, resulting in a caramelized and flavorful outer layer with moist and flaky flesh. This dish is a perfect choice for seafood lovers looking for a quick and easy yet impressive meal.",
    instruction: "Lorem ipsum",
  },
];

export default API;
